### ISSUE TITLE
Did I crash the web server with this?

### ISSUE THREAD

**Issue by jabowery** [rtestardi/calchemy#193]
Earlier today I was able to calculate the answer to this:

`(6ft)^2*pi;32g algae/m^2/day;416ppm(co2/air)*1.98kg/m^3;.505carbon/algae;.27 carbon/co2?L air/sec`

However, when I went back to the site, and entered it, the following sequence of events transpired:

The form popped.  
Pasted the formula in.
Clicked Enter.
Nothing happened.
Unsure if I had done something wrong, I tried a few things -- not sure the exact sequence.
Eventually, the day's prior history with "Delete" to the right for each entry. 
I realized then that my history must have been getting loaded from somewhere -- presumably cookies or a database backend -- but I had been doing things during that time.
Then the site froze.
The the site went dead with:
```
This site can’t be reachedThe connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET
```

**Comment by rtestardi** [comment]
Hi James,

The history is stored on your local computer, similar to a cookie (using a slightly different mechanism).  Likewise, all the calculations happen on your local computer as well, inside your web browser.

Once you have the webpage loaded and visible in your browser, the "server" is not used (unless you hit "Refresh", in which case the webpage will be reloaded from the server).  So you can't crash the server. :-)

Were you accessing calchemy.html from github (https://rtestardi.github.io/calchemy/calchemy.html) or from calchemy.com (http://www.calchemy.com/uclive.htm)?

**Comment by rtestardi** [comment]
PS I was able to run your calculation just now:

(6ft)^2*pi;32g algae/m^2/day;416ppm(co2/air)*1.98kg/m^3;.505carbon/algae;.27 carbon/co2?L air/sec
> ((6 foot)^2 * pi * ((32 gramm algae / (meter)^2) / day) / (416 ppm (co2 / air) * 1.98 kilo~gramm / (meter)^3)) * (.505 carbon / algae) / (.27 carbon / co2) ? liter air / second
> ((6 foot)^2 * pi * ((32 gramf algae / (meter)^2) / day) / (416 ppm (co2 / air) * 1.98 kilo~gramf / (meter)^3)) * (.505 carbon / algae) / (.27 carbon / co2) ? liter air / second
= 8.83665 L air/sec

**Comment by jabowery** [comment]
I was using:

http://www.calchemy.com/uclive.htm

The interruption of "service" applied across browsers:  Brave and Firefox.

I didn't have difficult accessing other websites, or may be my internet connection had a glitch that ended just as I was trying to access another website.  

I was then able to access the calculator again and then it went away again -- same phenomenon -- and it's now back.  So I'm going to keep open the DevTools in Brave, looking at the Network tab.

At present its working ok but the Network log shows a 404 on "custom.js". See attached.

[www.calchemy.com-1593916959694.log](https://github.com/rtestardi/calchemy/files/4874329/www.calchemy.com-1593916959694.log)

**Comment by rtestardi** [comment]
Custom.js off the website should be 404, so that is not a problem -- if you download calchemy.html  to your local computer, you can run it from there and then you can use custom.js in the same directory to load custom units (see the online help).  The only disadvantage to running calchemy.html from your local computer is that you won't get automatic updates (you'll have to re-download it periodically).  Anyway, let us know if you have any further issues.  You can always try the github location for calchemy.html (above) as a fallback if the calchemy.com location has issues.

**Comment by jabowery** [comment]
It's happening again but this time I was able to watch what was happening in Firefox's Web Developer Tools ->  Network page.  Which is nothing.  The only thing that shows up is the GET of www.calchemy.com/uclive.htm and then it goes silent.

So I closed the browser, brought up Wireshark and tried again to capture things at the packet level which I've screenshot and provided below in the event it might be beneficial.  I'm not having this trouble with any other sites, otherwise I wouldn't bother you with this.

![Capture](https://user-images.githubusercontent.com/57646/86546293-cc2f2f80-bef9-11ea-878d-b3d5321c89d9.PNG)

**Comment by rtestardi** [comment]
Next time it happens, can you try: https://rtestardi.github.io/calchemy/calchemy.html

If that works, then the issue is with calchemy.com hosting of uclive.html.

Basically, the server here is used for nothing more than to "serve" the webpage -- once your browser has a copy of the webpage, everything else runs in your browser.

Thanks.
